project:
  type: website
  pre-render: filters/pre-render.lua
  preview:
    port: 4200

website:
  title: "Ravel: Language Server, Formatter, and Linter for R"
  description: >-
    Ravel is a language server, formatter, and linter for R.

  site-url: "https://jolars.github.io/ravel"
  repo-url: "https://github.com/jolars/ravel"
  issue-url: "https://github.com/jolars/ravel/issues"

  repo-actions: [edit, issue]

  search: true

  # image: images/og.png
  image-alt: "Ravel logo"

  twitter-card: true

  open-graph:
    locale: en_US
    site-name: "Ravel"

  page-footer:
    left: "ravel v{{< meta version >}} | Copyright 2026, Johan Larsson"
    right:
      - icon: github
        href: "https://github.com/jolars/ravel"
        aria-label: "Source for this webpage"

  navbar:
    logo: images/logo-with-text.svg
    logo-alt: "Ravel logo"

    title: false

    tools:
      - icon: github
        href: "https://github.com/jolars/ravel"

    left:
      - href: index.qmd
        text: Overview
      - href: getting-started.qmd
        text: Getting Started
      - text: Help
        menu:
          - text: Report a bug
            icon: "bug"
            href: "https://github.com/jolars/ravel/issues"
          - text: Ask a question
            icon: "chat-right-text"
            href: "https://github.com/jolars/ravel/discussions"

# resources:
# - "apple-touch-icon.png"
# - "favicon-96x96.png"
# - "favicon.ico"
# - "favicon.svg"
# - "site.webmanifest"
# - "web-app-manifest-192x192.png"
# - "web-app-manifest-512x512.png"

highlight-style: breeze

format:
  html:
    toc: true
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    html-math-method: katex
    pagetitle: "{{< meta title >}}"
    code-copy: true
    include-in-header: _includes/social-extra.html

toc: true
date-format: "D MMMM YYYY"

filters:
  - filters/pre-render.lua
  - filters/promote-heading-to-title.lua
