use rowan::Language;

#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u16)]
pub enum SyntaxKind {
    ROOT,
    BINARY_EXPR,
    ASSIGNMENT_EXPR,
    PAREN_EXPR,
    IF_EXPR,
    FOR_EXPR,
    WHILE_EXPR,
    FUNCTION_EXPR,
    BLOCK_EXPR,
    UNARY_EXPR,
    IDENT,
    INT,
    FLOAT,
    STRING,
    COMMENT,
    TILDE,
    USER_OP,
    LBRACK2,
    RBRACK2,
    PLUS,
    MINUS,
    STAR,
    SLASH,
    CARET,
    PIPE,
    COLON,
    COLON2,
    COLON3,
    DOLLAR,
    AT,
    SEMICOLON,
    COMMA,
    OR,
    OR2,
    AND,
    AND2,
    EQUAL2,
    NOT_EQUAL,
    BANG,
    LESS_THAN,
    LESS_THAN_OR_EQUAL,
    GREATER_THAN,
    GREATER_THAN_OR_EQUAL,
    LPAREN,
    RPAREN,
    IF_KW,
    ELSE_KW,
    FOR_KW,
    WHILE_KW,
    FUNCTION_KW,
    IN_KW,
    LBRACE,
    RBRACE,
    WHITESPACE,
    NEWLINE,
    ASSIGN_LEFT,
    SUPER_ASSIGN,
    ASSIGN_RIGHT,
    SUPER_ASSIGN_RIGHT,
    ASSIGN_EQ,
    CALL_EXPR,
    ARG_LIST,
    ARG,
    ERROR,
}

impl From<SyntaxKind> for rowan::SyntaxKind {
    fn from(kind: SyntaxKind) -> Self {
        Self(kind as u16)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum RLanguage {}

impl Language for RLanguage {
    type Kind = SyntaxKind;

    fn kind_from_raw(raw: rowan::SyntaxKind) -> Self::Kind {
        match raw.0 {
            0 => SyntaxKind::ROOT,
            1 => SyntaxKind::BINARY_EXPR,
            2 => SyntaxKind::ASSIGNMENT_EXPR,
            3 => SyntaxKind::PAREN_EXPR,
            4 => SyntaxKind::IF_EXPR,
            5 => SyntaxKind::FOR_EXPR,
            6 => SyntaxKind::WHILE_EXPR,
            7 => SyntaxKind::FUNCTION_EXPR,
            8 => SyntaxKind::BLOCK_EXPR,
            9 => SyntaxKind::UNARY_EXPR,
            10 => SyntaxKind::IDENT,
            11 => SyntaxKind::INT,
            12 => SyntaxKind::FLOAT,
            13 => SyntaxKind::STRING,
            14 => SyntaxKind::COMMENT,
            15 => SyntaxKind::TILDE,
            16 => SyntaxKind::USER_OP,
            17 => SyntaxKind::LBRACK2,
            18 => SyntaxKind::RBRACK2,
            19 => SyntaxKind::PLUS,
            20 => SyntaxKind::MINUS,
            21 => SyntaxKind::STAR,
            22 => SyntaxKind::SLASH,
            23 => SyntaxKind::CARET,
            24 => SyntaxKind::PIPE,
            25 => SyntaxKind::COLON,
            26 => SyntaxKind::COLON2,
            27 => SyntaxKind::COLON3,
            28 => SyntaxKind::DOLLAR,
            29 => SyntaxKind::AT,
            30 => SyntaxKind::SEMICOLON,
            31 => SyntaxKind::COMMA,
            32 => SyntaxKind::OR,
            33 => SyntaxKind::OR2,
            34 => SyntaxKind::AND,
            35 => SyntaxKind::AND2,
            36 => SyntaxKind::EQUAL2,
            37 => SyntaxKind::NOT_EQUAL,
            38 => SyntaxKind::BANG,
            39 => SyntaxKind::LESS_THAN,
            40 => SyntaxKind::LESS_THAN_OR_EQUAL,
            41 => SyntaxKind::GREATER_THAN,
            42 => SyntaxKind::GREATER_THAN_OR_EQUAL,
            43 => SyntaxKind::LPAREN,
            44 => SyntaxKind::RPAREN,
            45 => SyntaxKind::IF_KW,
            46 => SyntaxKind::ELSE_KW,
            47 => SyntaxKind::FOR_KW,
            48 => SyntaxKind::WHILE_KW,
            49 => SyntaxKind::FUNCTION_KW,
            50 => SyntaxKind::IN_KW,
            51 => SyntaxKind::LBRACE,
            52 => SyntaxKind::RBRACE,
            53 => SyntaxKind::WHITESPACE,
            54 => SyntaxKind::NEWLINE,
            55 => SyntaxKind::ASSIGN_LEFT,
            56 => SyntaxKind::SUPER_ASSIGN,
            57 => SyntaxKind::ASSIGN_RIGHT,
            58 => SyntaxKind::SUPER_ASSIGN_RIGHT,
            59 => SyntaxKind::ASSIGN_EQ,
            60 => SyntaxKind::CALL_EXPR,
            61 => SyntaxKind::ARG_LIST,
            62 => SyntaxKind::ARG,
            63 => SyntaxKind::ERROR,
            _ => SyntaxKind::ERROR,
        }
    }

    fn kind_to_raw(kind: Self::Kind) -> rowan::SyntaxKind {
        kind.into()
    }
}

pub type SyntaxNode = rowan::SyntaxNode<RLanguage>;
